1.- Importar librerías

In [1]:
import pandas as pd
import numpy as np
!pip install scikit-learn
import sklearn
from sklearn.preprocessing import MinMaxScaler

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

2.- Leer el archivo csv y guardarlo en un dataframe

In [2]:
EmpleadosAttrition = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Reto empleados/empleadosRETO.csv')
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,1,997,4,Male,...,22,4,3,80,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,1,178,2,Male,...,20,4,4,80,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,1,1780,2,Male,...,13,3,2,80,1,3,3,0,1,Yes

3.- Eliminar las variables que no tienen relevancia a la salida

In [3]:
EmpleadosAttrition.drop(columns=['EmployeeCount','EmployeeNumber','Over18','StandardHours'], inplace=True)
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,No,22,4,3,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,No,20,4,4,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,No,13,3,2,1,3,3,0,1,Yes

4 y 5.- Crear columna con año de contratación

In [4]:
EmpleadosAttrition['Year'] = EmpleadosAttrition['HiringDate'].str.split('/', expand=True)[2]
EmpleadosAttrition['Year'] = pd.to_numeric(EmpleadosAttrition['Year']).astype('Int64')
EmpleadosAttrition.dtypes

Age                          int64
BusinessTravel              object
Department                  object
DistanceFromHome            object
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
Gender                      object
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
NumCompaniesWorked           int64
HiringDate                  object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
Attrition                   object
Year                         Int64
dtype: object

6.- Crear columna de años en la compañía, hasta el 2018

In [5]:
EmpleadosAttrition['YearsAtCompany']= 2018 - EmpleadosAttrition['Year']
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,4,3,32,1,2,4,1,No,2013,5
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,4,7,0,3,2,0,No,2015,3
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,3,2,1,3,3,0,1,Yes,2017,1

7 y 8.- Renombrar la columna DistanceFromHome

In [6]:
EmpleadosAttrition.rename(columns={'DistanceFromHome':'DistanceFromHome_km'}, inplace=True)
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,4,3,32,1,2,4,1,No,2013,5
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,4,7,0,3,2,0,No,2015,3
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,3,2,1,3,3,0,1,Yes,2017,1

9.- Crear variable DistanceFromHome, sólo numéricos

In [7]:
EmpleadosAttrition['DistanceFromHome']= EmpleadosAttrition['DistanceFromHome_km'].str.rstrip(' km').astype('Int64')
EmpleadosAttrition.head(5)

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,3,32,1,2,4,1,No,2013,5,1
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,7,0,3,2,0,No,2015,3,6
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,2,1,3,3,0,1,Yes,2017,1,7
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,...,4,18,4,3,6,4,No,2010,8,7
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,...,4,15,2,4,6,7,Yes,2011,7,15

10.- Borrar columnas sobrantes

In [8]:
EmpleadosAttrition.drop(columns=['HiringDate','Year','DistanceFromHome_km'], inplace=True)
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,2,Medical,4,Male,3,4,Research Director,...,4,3,32,1,2,4,1,No,5,1
1,36,Travel_Rarely,Research & Development,2,Medical,2,Male,3,2,Manufacturing Director,...,4,4,7,0,3,2,0,No,3,6
2,21,Travel_Rarely,Sales,1,Marketing,2,Male,3,1,Sales Representative,...,3,2,1,3,3,0,1,Yes,1,7

11.- Creando variable de sueldo promedio por departamento

In [9]:
SueldoPromedioDepto= EmpleadosAttrition.groupby('Department')['MonthlyIncome'].mean().rename('SueldoPromedio')
SueldoPromedioDepto.head(3)

Department
Human Resources           6239.888889
Research & Development    6804.149813
Sales                     7188.250000
Name: SueldoPromedio, dtype: float64

12.- Escalar variable MonthlyIncome entre 0 y 1

In [10]:
# Para este tipo de rango se necesita hacer uso del "Escalamiento min - max"
scaler= MinMaxScaler()
EmpleadosAttrition['MonthlyIncome']= scaler.fit_transform(EmpleadosAttrition[['MonthlyIncome']])
EmpleadosAttrition['MonthlyIncome'].head()

0    0.864269
1    0.207340
2    0.088062
3    0.497574
4    0.664470
Name: MonthlyIncome, dtype: float64

13.- Convertir variables categóricas a numéricas

In [11]:
Categ_columns = ['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Attrition','OverTime']
EmpleadosAttrition_OH = pd.get_dummies(EmpleadosAttrition, columns= Categ_columns, dtype= np.int64)
EmpleadosAttrition_OH.head()

,Age,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,...,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Attrition_No,Attrition_Yes,OverTime_No,OverTime_Yes
0,50,2,4,3,4,4,0.864269,9,22,4,...,0,0,0,1,0,0,1,0,1,0
1,36,2,2,3,2,2,0.207340,6,20,4,...,0,0,0,1,0,0,1,0,1,0
2,21,1,2,3,1,2,0.088062,1,13,3,...,0,0,1,0,0,1,0,1,1,0
3,52,4,2,3,3,2,0.497574,7,19,3,...,0,0,0,0,0,1,1,0,1,0
4,33,1,2,3,3,3,0.664470,7,12,3,...,0,0,0,0,1,0,0,1,0,1

In [12]:
# Para observar las nuevas columnas
EmpleadosAttrition_OH.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 48 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                400 non-null    int64
 1   Education                          400 non-null    int64
 2   EnvironmentSatisfaction            400 non-null    int64
 3   JobInvolvement                     400 non-null    int64
 4   JobLevel                           400 non-null    int64
 5   JobSatisfaction                    400 non-null    int64
 6   MonthlyIncome                      400 non-null    float64
 7   NumCompaniesWorked                 400 non-null    int64
 8   PercentSalaryHike                  400 non-null    int64
 9   PerformanceRating                  400 non-null    int64
 10  RelationshipSatisfaction           400 non-null    int64
 11  TotalWorkingYears                  400 non-null    int64
 12  TrainingTimesLastYear              400 non-null    int64
 13  WorkLifeBalance                    400 non-null    int64
 14  YearsInCurrentRole                 400 non-null    int64
 15  YearsSinceLastPromotion            400 non-null    int64
 16  YearsAtCompany                     400 non-null    Int64
 17  DistanceFromHome                   400 non-null    Int64
 18  BusinessTravel_Non-Travel          400 non-null    int64
 19  BusinessTravel_Travel_Frequently   400 non-null    int64
 20  BusinessTravel_Travel_Rarely       400 non-null    int64
 21  Department_Human Resources         400 non-null    int64
 22  Department_Research & Development  400 non-null    int64
 23  Department_Sales                   400 non-null    int64
 24  EducationField_Human Resources     400 non-null    int64
 25  EducationField_Life Sciences       400 non-null    int64
 26  EducationField_Marketing           400 non-null    int64
 27  EducationField_Medical             400 non-null    int64
 28  EducationField_Other               400 non-null    int64
 29  EducationField_Technical Degree    400 non-null    int64
 30  Gender_Female                      400 non-null    int64
 31  Gender_Male                        400 non-null    int64
 32  JobRole_Healthcare Representative  400 non-null    int64
 33  JobRole_Human Resources            400 non-null    int64
 34  JobRole_Laboratory Technician      400 non-null    int64
 35  JobRole_Manager                    400 non-null    int64
 36  JobRole_Manufacturing Director     400 non-null    int64
 37  JobRole_Research Director          400 non-null    int64
 38  JobRole_Research Scientist         400 non-null    int64
 39  JobRole_Sales Executive            400 non-null    int64
 40  JobRole_Sales Representative       400 non-null    int64
 41  MaritalStatus_Divorced             400 non-null    int64
 42  MaritalStatus_Married              400 non-null    int64
 43  MaritalStatus_Single               400 non-null    int64
 44  Attrition_No                       400 non-null    int64
 45  Attrition_Yes                      400 non-null    int64
 46  OverTime_No                        400 non-null    int64
 47  OverTime_Yes                       400 non-null    int64
dtypes: Int64(2), float64(1), int64(45)
memory usage: 150.9 KB

In [13]:
# Convertir las columnas de clase binaria en una sola columna, principalmente la
# variable de salida

EmpleadosAttrition_OH.drop(columns=['Attrition_No','Gender_Male','OverTime_No'])

# # # En las columnas restantes:
# Attrition_yes ----> 1, Attrition ; 0, Not Attrition
# Gender_Female ----> 1, Female ; 0, Male
# OverTime_yes      ----> 1, OverTime ; 0, No OverTime

,Age,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Attrition_Yes,OverTime_Yes
0,50,2,4,3,4,4,0.864269,9,22,4,...,0,1,0,0,0,1,0,0,0,0
1,36,2,2,3,2,2,0.207340,6,20,4,...,1,0,0,0,0,1,0,0,0,0
2,21,1,2,3,1,2,0.088062,1,13,3,...,0,0,0,0,1,0,0,1,1,0
3,52,4,2,3,3,2,0.497574,7,19,3,...,0,0,0,0,0,0,0,1,0,0
4,33,1,2,3,3,3,0.664470,7,12,3,...,0,0,0,0,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,33,3,3,3,1,4,0.075248,5,13,3,...,0,0,0,0,0,0,1,0,1,1
396,31,3,2,1,2,3,0.187197,3,11,3,...,0,0,0,1,0,0,1,0,1,1
397,37,3,2,3,3,4,0.589327,1,14,3,...,0,1,0,0,0,1,0,0,0,1
398,38,2,4,3,1,3,0.121124,7,19,3,...,0,0,0,0,0,0,1,0,0,0
399,33,3,4,3,1,2,0.092122,1,13,3,...,0,0,1,0,0,0,1,0,0,0

14.- Correlación lineal respecto a variable Attrition

In [14]:
corr = EmpleadosAttrition_OH.corr()['Attrition_Yes'].drop('Attrition_Yes')
print('Correlación de cada variable de entrada respecto a la salida: \n', corr)

Correlación de cada variable de entrada respecto a la salida:
 Age                                 -0.212121
Education                           -0.055531
EnvironmentSatisfaction             -0.124327
JobInvolvement                      -0.166785
JobLevel                            -0.214266
JobSatisfaction                     -0.164957
MonthlyIncome                       -0.194936
NumCompaniesWorked                  -0.009082
PercentSalaryHike                   -0.060880
PerformanceRating                   -0.006471
RelationshipSatisfaction            -0.030945
TotalWorkingYears                   -0.213329
TrainingTimesLastYear               -0.070884
WorkLifeBalance                     -0.021723
YearsInCurrentRole                  -0.203918
YearsSinceLastPromotion             -0.069000
YearsAtCompany                      -0.176001
DistanceFromHome                     0.052732
BusinessTravel_Non-Travel           -0.100698
BusinessTravel_Travel_Frequently     0.035387
BusinessTravel_Travel_Rarely         0.042755
Department_Human Resources           0.023389
Department_Research & Development   -0.072269
Department_Sales                     0.066116
EducationField_Human Resources       0.043404
EducationField_Life Sciences        -0.027457
EducationField_Marketing             0.016768
EducationField_Medical              -0.054144
EducationField_Other                -0.004275
EducationField_Technical Degree      0.129104
Gender_Female                        0.028839
Gender_Male                         -0.028839
JobRole_Healthcare Representative   -0.103274
JobRole_Human Resources              0.032714
JobRole_Laboratory Technician        0.125264
JobRole_Manager                     -0.089885
JobRole_Manufacturing Director      -0.042404
JobRole_Research Director           -0.116263
JobRole_Research Scientist           0.007977
JobRole_Sales Executive             -0.003115
JobRole_Sales Representative         0.191294
MaritalStatus_Divorced              -0.107869
MaritalStatus_Married               -0.094734
MaritalStatus_Single                 0.205849
Attrition_No                        -1.000000
OverTime_No                         -0.324777
OverTime_Yes                         0.324777
Name: Attrition_Yes, dtype: float64

15.- Seleccionar aquellas variables que tienen una correlación mayor a 0.1

In [15]:
# Primero se seleccionan las variables que cumplen el requisito usando el índice
Variables_corr = corr[corr.abs() > 0.1].index

# Ahora tomar únicamente las columnas que aparecen en la lista anterior y agregar
# la variable de salida
EmpleadosAttritionFinal = EmpleadosAttrition_OH[Variables_corr.tolist() + ['Attrition_Yes']]
EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,TotalWorkingYears,YearsInCurrentRole,YearsAtCompany,BusinessTravel_Non-Travel,...,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single,Attrition_No,OverTime_No,OverTime_Yes,Attrition_Yes
0,50,4,3,4,4,0.864269,32,4,5,0,...,0,0,1,0,1,0,1,1,0,0
1,36,2,3,2,2,0.207340,7,2,3,0,...,0,0,0,0,1,0,1,1,0,0
2,21,2,3,1,2,0.088062,1,0,1,0,...,0,0,0,1,0,1,0,1,0,1
3,52,2,3,3,2,0.497574,18,6,8,0,...,1,0,0,0,0,1,1,1,0,0
4,33,2,3,3,3,0.664470,15,6,7,0,...,0,0,0,0,0,0,0,0,1,1

16.- Obtener los componentes principales (PCA) del nuevo frame

In [16]:
# Importar PCA
from sklearn.decomposition import PCA

In [17]:
# Crear la instancia PCA y aplicarla al Dataframe
pca = PCA()
pca.fit(EmpleadosAttritionFinal)

print('Componentes principales: ', pca.components_)

Componentes principales:  [[ 6.86186586e-01 -2.21446035e-03  3.11643996e-04  7.10759557e-02
   7.94893567e-04  1.58580123e-02  6.38114553e-01  1.53884100e-01
   3.04351232e-01 -1.50530610e-03 -1.08654476e-03  3.14680878e-03
  -6.54687342e-03  8.30826284e-03 -6.01985627e-03  4.19169082e-04
  -5.09018133e-03  8.50057188e-03  1.84607653e-03 -1.84607653e-03
  -8.50057188e-03]
 [-5.95807818e-01 -2.45158294e-03 -5.32305758e-03  3.81575436e-02
   5.51621729e-03  8.51232261e-03  2.25189904e-01  3.82892290e-01
   6.67838341e-01  1.65583281e-03  3.16110746e-03 -2.59188691e-03
  -3.70469601e-03  5.21025428e-03 -7.07574112e-04  3.57172691e-03
  -2.61850132e-03  2.21667290e-03 -1.49974197e-03  1.49974197e-03
  -2.21667290e-03]
 [-4.16534249e-01 -9.98794768e-03 -1.26265717e-02  6.19327256e-02
  -1.77626941e-02  1.52952701e-02  7.25774878e-01 -3.30317378e-01
  -4.30656559e-01  2.89923345e-04 -3.43176478e-03  2.13962855e-03
  -1.00246166e-02  9.28273691e-03  2.55027248e-03 -8.12998528e-03
   1.19684263e-02 -6.83443621e-03 -3.06012852e-03  3.06012852e-03
   6.83443621e-03]
 [-1.82223970e-02 -2.90451531e-03 -1.45010695e-02 -5.69815691e-03
   3.51959630e-02 -2.31281475e-03  6.51734934e-02  8.47362240e-01
  -5.24296390e-01  1.46733272e-03 -1.60008076e-03  3.79096179e-03
  -1.03478337e-02  1.08823505e-02 -2.74432408e-03 -1.15010036e-02
  -2.97792727e-03  1.74922872e-02  2.27789789e-03 -2.27789789e-03
  -1.74922872e-02]
 [-2.17533665e-03 -4.54648229e-01 -3.35136173e-02  5.32235485e-02
   8.83647795e-01  6.69204744e-03 -2.27389538e-03 -3.57587605e-02
   6.63490338e-03  1.95636137e-02  1.70829611e-02  9.90954950e-03
  -1.78938525e-02 -8.71540177e-03 -8.73781714e-03  2.37308686e-02
  -1.12791139e-03  3.56049579e-02  3.73037818e-02 -3.73037818e-02
  -3.56049579e-02]
 [-6.72415719e-03  8.83856770e-01  1.01226620e-02 -3.20732357e-02
   4.51267529e-01 -8.19942353e-03  1.59579626e-02 -1.93278598e-02
   6.46376803e-04  3.67214469e-03 -1.07767000e-02 -5.35728637e-03
   1.78158445e-04 -1.85084802e-02 -1.81361641e-02  1.97706283e-02
  -1.24400813e-02  7.46936968e-02 -1.93495774e-02  1.93495774e-02
  -7.46936968e-02]
 [-5.40762771e-03  3.41306948e-02  3.72528871e-01  8.51408466e-01
  -3.95179997e-02  1.80509210e-01 -8.96013694e-02 -3.06115826e-03
  -2.26422315e-02  1.64235162e-02 -1.65387745e-02  1.19657945e-02
  -1.61520557e-01  1.35467567e-01 -2.22287787e-02 -3.38046286e-02
  -5.37091217e-03  1.30694777e-01  7.57669459e-02 -7.57669459e-02
  -1.30694777e-01]
 [-1.08744267e-02 -5.46874139e-02  8.78660557e-01 -3.88026593e-01
   1.48037583e-02 -8.72230800e-02  5.18879639e-02  3.35698382e-03
   9.85240170e-04 -4.72985818e-02 -1.54966075e-02  5.92639622e-03
   7.92327186e-02 -4.92613424e-02  4.06320415e-03  5.21712988e-03
  -8.31810942e-02  1.31663782e-01  7.38239561e-02 -7.38239561e-02
  -1.31663782e-01]
 [-6.68173159e-03  1.25776845e-02 -2.34565379e-01 -8.05657558e-02
  -7.52936092e-02 -1.57017393e-02  7.25735788e-03 -1.35042323e-02
   3.29848166e-03  6.16798407e-02 -2.94194864e-02  1.37748584e-02
   3.63662532e-02 -2.04458936e-02  1.07845696e-03  9.54890093e-02
  -1.08055272e-01  2.79212185e-01  6.11886212e-01 -6.11886212e-01
  -2.79212185e-01]
 [ 6.39456211e-03  4.06527511e-02  7.36207324e-02 -3.51216135e-02
   4.10906378e-02 -4.38124238e-03 -1.98798401e-04  7.49711013e-03
   1.18305159e-02 -3.99249348e-02  4.19180271e-03 -3.51587194e-02
  -4.59504664e-02 -1.48410554e-02  9.37701331e-02 -6.02642957e-01
   6.82426511e-01 -1.76767821e-01  2.05424721e-01 -2.05424721e-01
   1.76767821e-01]
 [ 2.31921366e-03  7.03443875e-02  1.37265699e-01  1.18072378e-01
   5.91364857e-02  3.16818345e-02 -6.27088594e-04  2.12977790e-02
  -1.30075123e-02 -7.05000826e-02  4.80363029e-02 -1.38556863e-01
   2.57585585e-01  2.52244258e-02  2.65832290e-02  2.67631211e-01
  -2.16341879e-01 -5.56312935e-01  2.50571168e-01 -2.50571168e-01
   5.56312935e-01]
 [-4.74021004e-04 -2.11853862e-02 -6.66249018e-03  8.72253805e-02
  -7.55598473e-03  3.79918312e-02 -3.10217028e-03  2.23765338e-03
  -4.98756342e-03  3.13757126e-01 -1.41233797e-01 -3.01054149e-01
   7.81797439e-01  1.47126780e-01 -1.87134925e-01  5.80636429e-02
   2.55494132e-01  1.30558587e-01 -7.32170325e-02  7.32170325e-02
  -1.30558587e-01]
 [ 3.43247265e-03  1.92420301e-03  6.12997062e-02 -3.57394678e-02
  -1.85389464e-02 -1.61377016e-02  2.74170276e-03  9.17976596e-03
  -2.53041626e-03  9.66970683e-02 -6.89515815e-02  4.67482333e-02
  -2.48937528e-01 -1.98413311e-02  1.03417810e-01  7.31751840e-01
   6.07646991e-01 -6.58442429e-03  7.61775657e-03 -7.61775657e-03
   6.58442429e-03]
 [-2.87282011e-03  1.25716435e-02  2.73204764e-02  9.50603109e-02
  -7.80890515e-03 -4.76134043e-02 -3.03729161e-03  5.54389303e-03
  -2.02122132e-03  2.40183549e-01  4.96135666e-03  8.37531249e-01
   2.48414650e-01 -3.40329275e-01 -1.99248259e-01 -1.49322305e-02
   3.99264133e-02 -6.77683685e-02  1.16513471e-02 -1.16513471e-02
   6.77683685e-02]
 [ 3.50973052e-03  1.13640615e-02  5.72741010e-02 -4.85994934e-02
  -3.30680185e-03 -1.26471725e-02  5.44721449e-03  4.94597548e-04
   1.27175604e-03  8.95667166e-01  4.97036250e-02 -1.77871385e-01
  -2.68000776e-01 -8.83286669e-02  1.74085013e-01 -1.05264084e-01
  -1.49855260e-01 -8.41583981e-02  5.05834826e-03 -5.05834826e-03
   8.41583981e-02]
 [ 1.87334619e-03  1.66957186e-02 -1.55470325e-03 -1.20777681e-01
   1.60519397e-02  5.94427983e-02  7.16908312e-04 -7.42482664e-03
   5.98789032e-03  9.85933928e-02  2.74065980e-01  3.65171061e-01
   8.00197340e-02  8.20624478e-01  2.88377358e-01 -1.18951354e-03
  -5.70816560e-03 -3.33941158e-03  2.93722548e-03 -2.93722548e-03
   3.33941158e-03]
 [ 1.15190354e-03  4.65716653e-03 -4.73141744e-03  1.11894908e-01
  -1.79611838e-02 -2.94652190e-02  1.08399914e-04  4.29105324e-03
  -7.55283554e-03 -7.02098340e-02  7.65805594e-01 -9.41040414e-02
   2.25104153e-01 -3.56042559e-01  4.24318073e-01  5.24425556e-02
   5.90850827e-02  1.01003534e-01 -2.99662116e-02  2.99662116e-02
  -1.01003534e-01]
 [ 1.52888030e-03 -3.94817532e-03 -1.96525018e-02  7.09032266e-02
   1.57295407e-02  2.78739592e-03 -2.87946419e-03  4.06635264e-03
   1.20318752e-03 -6.60981902e-02 -5.54014914e-01  1.00525477e-01
   1.82905614e-01 -1.34355552e-01  7.81410945e-01 -2.85136185e-02
  -8.01335391e-02  2.50679314e-02 -3.37646335e-02  3.37646335e-02
  -2.50679314e-02]
 [ 2.61730202e-04 -1.59930284e-03  5.61181510e-03 -1.90308264e-01
   1.72024071e-03  9.74332402e-01 -2.00404903e-03  2.33445783e-03
  -1.02685627e-03  5.16900579e-04  1.27679273e-02  2.84372049e-02
   4.87233541e-03 -1.15411510e-01 -1.44278529e-03  6.42190563e-03
   4.19659181e-03  3.32528031e-03 -2.54655894e-03  2.54655894e-03
  -3.32528031e-03]
 [ 4.92444700e-18 -1.68345967e-16 -8.74601045e-17 -3.18593124e-15
   5.89689131e-18  1.59318195e-14 -2.34594778e-17  6.34839980e-17
  -1.93571201e-17 -3.92196063e-16  2.50031559e-17  6.61642877e-16
   5.00852412e-16 -1.92774670e-15  4.65104321e-16 -4.55523323e-17
  -1.17889167e-17  6.47969158e-01 -2.83082975e-01 -2.83082975e-01
   6.47969158e-01]
 [ 2.17984460e-17 -2.10617302e-16  2.03113918e-16 -1.29787816e-15
   4.58471753e-17  9.02265369e-15 -1.03152724e-16 -1.36263433e-17
   3.50058574e-17  5.62126245e-16 -6.20759080e-16  1.96000155e-16
   1.70387924e-16 -1.17804998e-15  1.36224684e-16 -1.29791700e-16
  -1.14379562e-16  2.83082975e-01  6.47969158e-01  6.47969158e-01
   2.83082975e-01]]

In [18]:
# Evaluación de los componentes
print(pca.explained_variance_)

[1.22318525e+02 4.65655502e+01 1.52049441e+01 4.05429547e+00
 1.25886621e+00 1.24943515e+00 5.83223728e-01 5.51008072e-01
 4.39608867e-01 2.62197573e-01 1.70897842e-01 1.26533360e-01
 1.22987491e-01 8.87045172e-02 7.88871042e-02 5.47016395e-02
 5.01178436e-02 4.20776198e-02 4.97585842e-03 2.79273469e-17
 1.02365666e-17]

In [19]:
# Evaluación de los componentes en porcentaje
print(pca.explained_variance_ratio_)

[6.33028431e-01 2.40988167e-01 7.86893230e-02 2.09819756e-02
 6.51494205e-03 6.46613398e-03 3.01832614e-03 2.85160220e-03
 2.27508393e-03 1.35693688e-03 8.84438335e-04 6.54841236e-04
 6.36490493e-04 4.59067679e-04 4.08260153e-04 2.83094429e-04
 2.59372159e-04 2.17762024e-04 2.57512903e-05 1.44530885e-19
 5.29767481e-20]

In [20]:
# Aplicar componentes al conjunto de datos
EmpleadosAttritionPCA = pca.transform(EmpleadosAttritionFinal)
EmpleadosAttritionPCA

array([[ 2.02537526e+01, -4.20770213e+00,  1.07199661e+01, ...,
         4.95510700e-02,  4.44089210e-16, -7.77156117e-16],
       [-6.38023268e+00, -3.69084813e+00, -1.58673261e-01, ...,
        -5.09080980e-02, -9.99200722e-16, -3.33066907e-16],
       [-2.15196873e+01,  1.74316443e+00,  3.22919951e+00, ...,
         1.83476075e-02,  4.99600361e-16,  5.55111512e-16],
       ...,
       [-6.42599804e-01,  3.42178720e+00, -3.34673013e+00, ...,
         2.51562991e-02,  3.33066907e-16,  6.66133815e-16],
       [-6.31172465e+00, -7.69731818e+00,  8.57978029e-01, ...,
         5.13043139e-02,  9.99200722e-16,  1.11022302e-16],
       [-5.58725240e+00,  3.52780517e+00, -2.06370625e+00, ...,
         2.12674921e-02,  3.33066907e-16, -5.55111512e-16]])

17.- Agregar el mínimo número de componentes que expliquen el 80% de la varianza

In [24]:
# Obteniendo los componentes mínimos para el 80% de varianza
sum_varianza = np.cumsum(pca.explained_variance_ratio_)
n_pca = np.argmax(sum_varianza >= 0.8) + 1

# Seleccionar los primeros PCA
pca_top = EmpleadosAttritionPCA[:, :n_pca]

In [26]:
# Nombrando dichos componentes
nombres_pca = [f'C{i}' for i in range(n_pca)]

# Convertir los componentes a un dataframe
pca_df = pd.DataFrame(pca_top, columns= nombres_pca)
pca_df.head()

          C0        C1
0  20.253753 -4.207702
1  -6.380233 -3.690848
2 -21.519687  1.743164
3  13.828621 -5.844077
4  -1.442927  4.143576

In [28]:
# Agregar dicho Dataframe a EmpleadosAttritionFinal
EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(**pca_df)
EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,TotalWorkingYears,YearsInCurrentRole,YearsAtCompany,BusinessTravel_Non-Travel,...,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single,Attrition_No,OverTime_No,OverTime_Yes,Attrition_Yes,C0,C1
0,50,4,3,4,4,0.864269,32,4,5,0,...,1,0,1,0,1,1,0,0,20.253753,-4.207702
1,36,2,3,2,2,0.207340,7,2,3,0,...,0,0,1,0,1,1,0,0,-6.380233,-3.690848
2,21,2,3,1,2,0.088062,1,0,1,0,...,0,1,0,1,0,1,0,1,-21.519687,1.743164
3,52,2,3,3,2,0.497574,18,6,8,0,...,0,0,0,1,1,1,0,0,13.828621,-5.844077
4,33,2,3,3,3,0.664470,15,6,7,0,...,0,0,0,0,0,0,1,1,-1.442927,4.143576

In [29]:
EmpleadosAttritionFinal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                400 non-null    int64
 1   EnvironmentSatisfaction            400 non-null    int64
 2   JobInvolvement                     400 non-null    int64
 3   JobLevel                           400 non-null    int64
 4   JobSatisfaction                    400 non-null    int64
 5   MonthlyIncome                      400 non-null    float64
 6   TotalWorkingYears                  400 non-null    int64
 7   YearsInCurrentRole                 400 non-null    int64
 8   YearsAtCompany                     400 non-null    Int64
 9   BusinessTravel_Non-Travel          400 non-null    int64
 10  EducationField_Technical Degree    400 non-null    int64
 11  JobRole_Healthcare Representative  400 non-null    int64
 12  JobRole_Laboratory Technician      400 non-null    int64
 13  JobRole_Research Director          400 non-null    int64
 14  JobRole_Sales Representative       400 non-null    int64
 15  MaritalStatus_Divorced             400 non-null    int64
 16  MaritalStatus_Single               400 non-null    int64
 17  Attrition_No                       400 non-null    int64
 18  OverTime_No                        400 non-null    int64
 19  OverTime_Yes                       400 non-null    int64
 20  Attrition_Yes                      400 non-null    int64
 21  C0                                 400 non-null    float64
 22  C1                                 400 non-null    float64
dtypes: Int64(1), float64(3), int64(19)
memory usage: 72.4 KB

18.- Guardar en un csv

In [30]:
EmpleadosAttritionFinal.to_csv('EmpleadosAttritionFinal.csv', index= False)